### ISSUE TITLE
structure superpositioning crashes when clicking on download.

### ISSUE THREAD

**Issue by j0kaso** [protwis/protwis#400] opened 2022-01-17 21:00 UTC
Hi!
Seems like the superpositioning is crashing. I had a testset of ~60 structures and when I reach this website:

`https://gproteindb.org/structure/superposition_workflow_results/full?
`

I get this server error:

> Server error
> There was an error handling your request. Either the url you entered is incorrect or it was something on our end.
> 
> If you believe this is an error on our end, please do not hesitate to contact us on info@gpcrdb.org.
> 
> Do you have a Github account? In that case you can directly report your issue on our GitHub issues page.

Thanks for looking into it

**Comment by AJK-dev** [comment] 2022-01-18 08:21
Hi Johanna, thanks for reporting this issue! We've recently refactored part of our superpositioning workflow and superpositioning of up to 100 structures should now be supported. However, it seems that you've uncovered a bug that might be related to a specific structure or a specific set of structures. Could you maybe share (here or via mail) the PDBs that you've selected, the reference, and the segment alignment, so we can dig deeper into this issue?

**Comment by j0kaso** [comment] 2022-01-18 08:59
Hi Albert - thanks for looking into this! 
I aligned to 3SN6 and used different segments, like all the TM regions.
Here is the 60 structure list: 7NA7,7EIB,7F2O,7F8W,7FIG,7EW4,7EW1,7EZM,7DB6,7F16,7EXD,7DH5,7EVW,7DTY,7DUQ,7MTS,7JHJ,7O7F,7E9H,7KH0,7CX2,7AUE,7E32,7E2X,7E33,7DFL,7CMV,7JVQ,7JVR,7L1V,7D77,7D68,7AD3,7CZ5,7D7M,6WHA,7CFN,6LFO,6VN7,6WPW,6WZG,6WWZ,6K42,6UVA,6OMM,6LI3,6PT0,6PB0,6PB1,6P9Y,6OSA,6OIJ,6NBI,6N4B,6NIY,6G79,6D9H,6DDF,4PXF,3SN6

**Comment by AJK-dev** [comment] 2022-01-19 15:48
@j0kaso The issue you reported is now fixed.

However, upon visual inspection of the results, we found a two additional issues:
- The first alternate model of an atom is skipped during super positioning (when present). This results in long bond lengths and incorrect placements of some atoms:  example is W162 in 4PXF 
_Alternate A_
`ATOM   1265  CA ATRP A 161     136.436 243.576  26.115  0.46 71.65           C`
_Alternate B_
`ATOM   1266  CA BTRP A 161      25.738  -3.374   3.145  0.54  4.50           C`
- Some structural alignments are not correct, this seems often the case with cross-class alignments - in this case class A 3SN6 vs class B1 structures 6NBI, 6VN7, 6WZG, 7DUQ or class D1 7AD3. 

The first one (the alternative positions/alternate models) can be fixed by updating BioPython. 
@pszgaspar Could you look into the second issue and maybe look into using the _GenericNumberingFromDB_ class for the superpositions workflow?

**Comment by AJK-dev** [comment] 2022-01-20 08:38
> The first alternate model of an atom is skipped during super positioning (when present). This results in long bond lengths and incorrect placements of some atoms: example is W161 in 4PXF

BioPython has been updated and thereby this issue has been resolved. However, the GN numbering only takes one alternate into account, so depending on the chosen alternate the GN might not be present in the B-factor column.

`ATOM   1265  CA ATRP A 161      25.773  -3.425   3.177  0.46 71.65           C  `
`ATOM   1266  CA BTRP A 161      25.738  -3.374   3.145  0.54  4.50           C  `

**Closed** 2022-04-04 14:49 UTC
Labels: bug

**Comment by AJK-dev** [comment] 2022-04-04 14:59
Although the primary issue was resolved, the other secondary issue is still open. Therefore I'm reopening this one after automatically closing it through the PR.

Still needs to be done:
> @pszgaspar Could you look into the second issue and maybe look into using the _GenericNumberingFromDB_ class for the superpositions workflow? Extra note which to a small extent resolves this issue: some B-factors can mimic GN positions, clearing all CA B-factors by setting to 0 should resolve this.

**Comment by pszgaspar** [comment] 2022-07-15 10:08
The secondary issue seems to be caused by a feature bug when cross-class superpositioning. Instead of cross-class equivalent generic numbers, class specific generic numbers get assigned in the pdb file bfactor field which are used for the superpositioning. A gn equivalent lookup or a dictionary should fix the issue.
